#!/bin/bash
# Creates an empty, history-less branch

if [ $# -ne 1 ]
then
	echo Usage: $0 branch_name
	exit
fi

git symbolic-ref HEAD refs/heads/$1
rm .git/index
git clean -dx --force

echo Empty branch $1 created
